# ------------------------------------------------------------------------------------------------------------------------
# GHA Reusable Called Workflow to deploy an already built Website App
# ------------------------------------------------------------------------------------------------------------------------
# You need to set up secrets in the GitHub Secrets Repository before running these workflows.
#   See readme.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: template.deploy.website
run-name: Deploy Website App
on:
  workflow_call:
    inputs:
      envCode:
        required: true
        type: string

# ------------------------------------------------------------------------------------------------------------------------
jobs:
  deploy:
    name: Deploy
    runs-on: windows-latest
    
    environment:
      name: ${{ inputs.envCode }}

    env:
      artifactName: websiteapp
      generatedAppEnvName: ${{ vars.ORG_NAME }}-${{ vars.APP_NAME }}-${{ inputs.envCode }}

    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3
      with:
        name: ${{ env.artifactName }}

    # - name: List Files
    #   run: 
    #     tree ${{ env.GITHUB_ACTION_PATH }}
    #   continue-on-error: true

    - name: Log into Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Azure Website Zip
      uses: Azure/webapps-deploy@v2
      with:
        app-name: ${{ env.generatedAppEnvName }}
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        package: .
